<a href="https://colab.research.google.com/github/Jpablosg/BioPPSPIAtechnology/blob/main/Bioinformatica_2_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Guardado en Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


#Generación de Secuencias Aleatorias

In [ ]:
#Importar el módulo random para generar números aleatorios
import random

#Definir nucleotidos para secuencia aleatoria
nucleotides=['T', 'C', 'A', 'G']
#Define the starts and stop codons
Start_codon=['ATG']
Stop_codons=['TAA', 'TAG','TGA']

#Generar longitud deseada de la secuencia
longitud = int(input("longitud de la secuencia de ADN: "))

#Crear secuencia de ADN aleatoria
secuencia_adn = ''.join(random.choice(nucleotides) for _ in range(longitud))

#Definir tabla de traducción del codigo genetico
genetic_code ={
  # U            C            A            G

#U
  'TTT':'F', 'TCT':'S', 'TAT':'Y', 'TGU':'C', #UxU
  'TTC':'F', 'TCC':'S', 'TAC':'Y', 'TGC':'C', #UxC
  'TTA':'L', 'TCA':'S', 'TAA':'-', 'TGA':'-', #UxA
  'TTG':'L', 'TCG':'S', 'TAG':'-', 'TGG':'W', #UxG
#C
  'CTT':'L', 'CCT':'P', 'CAT':'H', 'CGT':'R', #CxU
  'CTC':'L', 'CCC':'P', 'CAC':'H', 'CGC':'R', #CxC
  'CTA':'L', 'CCA':'P', 'CAA':'Q', 'CGA':'R', #CxA
  'CTG':'L', 'CCG':'P', 'CAG':'Q', 'CGG':'R', #CxG
#A
  'ATT':'I', 'ACU':'T', 'AAT':'N', 'AGT':'S', #AxU
  'ATC':'I', 'ACC':'T', 'AAC':'N', 'AGC':'S', #AxC
  'ATA':'I', 'ACA':'T', 'AAA':'K', 'AGA':'R', #AXA
  'ATG':'M', 'ACG':'T', 'AAG':'K', 'AGG':'R', #AxG
#G
  'GTT':'V', 'GCT':'A', 'GAT':'D', 'GGT':'G', #GxU
  'GTC':'V', 'GCC':'A', 'GAC':'D', 'GGC':'G', #GxC
  'GTA':'V', 'GCA':'A', 'GAA':'E', 'GGA':'G', #GxA
  'GTG':'V', 'GCG':'A', 'GAG':'E', 'GGG':'G', #GxG
}

#Tradu decir secuencia de ADN a proteínas
secuencia_proteinas = ''
i = 0

#Bucle para recorrer los codones en la secuencia de ADN
while i < len(secuencia_adn) - 2:
    codon = secuencia_adn[i:i+3]
    aminoacido = genetic_code.get(codon, 'X') #Busca el aminoácido correspondiente al codón utilizando
    secuencia_proteinas += aminoacido #Agrega el aminoácido a la secuencia de proteínas

    #if aminoacido == '*':
        #break #Si el aminoácido es un codón STOP, se detiene el bucle

    i += 3 #Irementa el índice en 3 para pasar al siguiente codón

print(len(secuencia_adn))
print(len(secuencia_proteinas))

longitud de la secuencia de ADN: 30000000
30000000
10000000


#Dataset de Nucleotidos (ADN)

In [ ]:
import numpy as np

def generar_ngramas(seq, n):
    ngramas = []  # Lista para almacenar los n-gramas
    k = 0  # Variable de índice para recorrer la secuencia
    for i in range((len(seq) + 1) // n):  # Bucle para generar los n-gramas
        ngrama = seq[k:k+n]  # Extrae el n-grama actual
        k += n  # Actualiza el índice
        ngramas.append(ngrama)  # Agrega el n-grama a la lista
    return ngramas

# Ruta específica para los archivos CSV
ruta_especifica = '/content/drive/MyDrive/Colab Notebooks/Entrenamiento IA/Datasets'

seq = secuencia_adn  # Variable que contiene la secuencia de ADN
n = 3  # Valor que indica la longitud de los n-gramas (trigramas en este caso)

ngramas = generar_ngramas(seq, n)  # Genera los n-gramas llamando a la función

# Convierte los n-gramas en una matriz NumPy
X_train = np.array([list(ngrama) for ngrama in ngramas])

# Convierte las letras en valores ASCII y crea una matriz NumPy
X_train = np.array([[ord(letra) for letra in ngrama] for ngrama in ngramas])

print("X_train:")
print(X_train)
print(len(X_train))

# Guardar X_train en un archivo CSV en la ruta especificada
np.savetxt(ruta_especifica + 'X_train.csv', X_train, delimiter=',')

print("X_train guardado en", ruta_especifica + 'X_train.csv')


X_train:
[[71 65 67]
 [71 65 84]
 [84 71 84]
 ...
 [84 67 65]
 [67 67 71]
 [84 84 67]]
10000000
X_train guardado en /content/drive/MyDrive/Colab Notebooks/Entrenamiento IA/DatasetsX_train.csv


#Dataset de Proteína (aminoácidos)

In [ ]:
import numpy as np

def generar_ngramas(seq, n):
    ngramas = []  # Lista para almacenar los n-gramas
    k = 0  # Variable de índice para recorrer la secuencia
    for i in range((len(seq) + 1) // n):  # Bucle para generar los n-gramas
        ngrama = seq[k:k+n]  # Extrae el n-grama actual
        k += n  # Actualiza el índice
        ngramas.append(ngrama)  # Agrega el n-grama a la lista
    return ngramas

# Ruta específica para los archivos CSV
ruta_especifica = '/content/drive/MyDrive/Colab Notebooks/Entrenamiento IA/Datasets'

protein_sequences = secuencia_proteinas
# Generar monogramas
monogramas = [c for seq in protein_sequences for c in seq]

# Crear el diccionario de caracteres
caracteres = sorted(list(set(monogramas)))
caracter_a_indice = {caracter: indice for indice, caracter in enumerate(caracteres)}

# Generar y_train
y_train = np.array([caracter_a_indice[caracter] for caracter in monogramas])
# print("y_train:")
# print(y_train)
print(len(y_train))

# Guardar y_train en un archivo CSV en la ruta especificada
nombre_archivo_y_train = ruta_especifica + "y_train.csv"
np.savetxt(nombre_archivo_y_train, y_train, delimiter=',')
print("y_train guardado en:", nombre_archivo_y_train)


10000000
y_train guardado en: /content/drive/MyDrive/Colab Notebooks/Entrenamiento IA/Datasetsy_train.csv


#Primer entrenamiento de la red neuronal Densa/perceptron

In [ ]:
import tensorflow as tf
import numpy as np

def model_checkpoint_callback(filepath):
    return tf.keras.callbacks.ModelCheckpoint(
        filepath=filepath,
        save_weights_only=True,
        monitor='val_loss',
        mode='min',
        verbose=1
    )

# Ruta específica donde se encuentran los archivos CSV
ruta_especifica = '/content/drive/MyDrive/Colab Notebooks/Entrenamiento IA/Datasets'

# Cargar los datos de entrenamiento X_train e y_train desde los archivos CSV
X_train = np.loadtxt(ruta_especifica + 'X_train.csv', delimiter=',')
y_train = np.loadtxt(ruta_especifica + 'y_train.csv', delimiter=',')

# Asegúrate de que los datos estén en la forma adecuada para la entrada del modelo
X_train = X_train.reshape(-1, 3, 1)

# Definir la arquitectura de la red neuronal
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(3, 1)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1, activation='linear')
])

# Compilar el modelo
model.compile(optimizer='adam', loss='mean_squared_error')

# Definir el número de épocas para el entrenamiento
num_epocas = 50

# Definir el callback ModelCheckpoint usando la función
checkpoint_filepath = "/content/drive/MyDrive/Colab Notebooks/Entrenamiento IA/checkpoint"
model_checkpoint_callback = model_checkpoint_callback(checkpoint_filepath)

# Entrenar el modelo con los datos cargados desde los archivos CSV y usando el callback
for epoch in range(num_epocas):
    print(f'Comenzando época {epoch + 1}')
    model.fit(X_train, y_train, epochs=1, callbacks=[model_checkpoint_callback], verbose=1)
    print(f'Época {epoch + 1} completada. Pesos guardados.')

# Predecir valores de y_train a partir de X_train
y_train_pred = model.predict(X_train)

# Guardar el modelo entrenado
model.save("/content/drive/MyDrive/Colab Notebooks/Entrenamiento IA/modelo_DNA2PROT.h5")



Comenzando época 1
312465/312500 [============================>.] - ETA: 0s - loss: 2.4568
Epoch 1: saving model to /content/drive/MyDrive/Colab Notebooks/Entrenamiento IA/checkpoint
312500/312500 [==============================] - 381s 1ms/step - loss: 2.4565
Época 1 completada. Pesos guardados.
Comenzando época 2
312481/312500 [============================>.] - ETA: 0s - loss: 0.4188
Epoch 1: saving model to /content/drive/MyDrive/Colab Notebooks/Entrenamiento IA/checkpoint
312500/312500 [==============================] - 368s 1ms/step - loss: 0.4188
Época 2 completada. Pesos guardados.
Comenzando época 3
312469/312500 [============================>.] - ETA: 0s - loss: 0.3764
Epoch 1: saving model to /content/drive/MyDrive/Colab Notebooks/Entrenamiento IA/checkpoint
312500/312500 [==============================] - 356s 1ms/step - loss: 0.3764
Época 3 completada. Pesos guardados.
Comenzando época 4
312474/312500 [============================>.] - ETA: 0s - loss: 0.1631
Epoch 1: saving

#Segundo Entrenamiento

In [ ]:
import tensorflow as tf
import numpy as np


# Cargar el modelo previamente entrenado
model = tf.keras.models.load_model("/content/drive/MyDrive/Colab Notebooks/Entrenamiento IA/modelo_DNA2PROT.h5")

# Ruta específica donde se encuentran los archivos CSV
ruta_especifica = '/content/drive/MyDrive/Colab Notebooks/Entrenamiento IA/Datasets'

# Cargar los datos de entrenamiento X_train e y_train desde los archivos CSV
X_train = np.loadtxt(ruta_especifica + 'X_train.csv', delimiter=',')
y_train = np.loadtxt(ruta_especifica + 'y_train.csv', delimiter=',')

# Asegúrate de que los datos estén en la forma adecuada para la entrada del modelo
X_train = X_train.reshape(-1, 3, 1)

# Definir el segundo número de épocas para el entrenamiento
num_epocas_segundo_entrenamiento = 50

# Definir el nuevo callback ModelCheckpoint sin usar la función
checkpoint_filepath_segundo_entrenamiento = "/content/drive/MyDrive/Colab Notebooks/Entrenamiento IA/checkpoint_segundo_entrenamiento"
model_checkpoint_callback_segundo_entrenamiento = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_filepath_segundo_entrenamiento,
    save_weights_only=True,
    monitor='val_loss',
    mode='min',
    verbose=1
)

# Entrenar el modelo nuevamente con los datos de entrenamiento y usando el nuevo callback
for epoch in range(num_epocas_segundo_entrenamiento):
    print(f'Segundo entrenamiento: Comenzando época {epoch + 1}')
    model.fit(X_train, y_train, epochs=1, callbacks=[model_checkpoint_callback_segundo_entrenamiento], verbose=1)
    print(f'Segundo entrenamiento: Época {epoch + 1} completada. Pesos guardados.')

# Predecir valores de y_train a partir de X_train en el segundo entrenamiento
y_train_pred_segundo_entrenamiento = model.predict(X_train)

# Guardar el modelo después del segundo entrenamiento
model.save("/content/drive/MyDrive/Colab Notebooks/Entrenamiento IA/modelo_DNA2PROT_segundo_entrenamiento.h5")


Segundo entrenamiento: Comenzando época 1
312492/312500 [============================>.] - ETA: 0s - loss: 0.6378
Epoch 1: saving model to /content/drive/MyDrive/Colab Notebooks/Entrenamiento IA/checkpoint_segundo_entrenamiento
312500/312500 [==============================] - 610s 2ms/step - loss: 0.6378
Segundo entrenamiento: Época 1 completada. Pesos guardados.
Segundo entrenamiento: Comenzando época 2
312488/312500 [============================>.] - ETA: 0s - loss: 0.4295
Epoch 1: saving model to /content/drive/MyDrive/Colab Notebooks/Entrenamiento IA/checkpoint_segundo_entrenamiento
312500/312500 [==============================] - 626s 2ms/step - loss: 0.4295
Segundo entrenamiento: Época 2 completada. Pesos guardados.
Segundo entrenamiento: Comenzando época 3
312492/312500 [============================>.] - ETA: 0s - loss: 0.3572
Epoch 1: saving model to /content/drive/MyDrive/Colab Notebooks/Entrenamiento IA/checkpoint_segundo_entrenamiento
312500/312500 [=========================

#Evaluación del modelo de DL

In [ ]:
#Evaluar el rendimiento de modelo cargado
import tensorflow as tf
model = tf.keras.models.load_model("/content/drive/MyDrive/Colab Notebooks/Entrenamiento IA/modelo_DNA2PROT.h5")
model.evaluate(X_train, y_train)

In [ ]:
#Evaluar el modelo de aprendizaje automático Utilizando los datos de entrenamiento
result = model.evaluate(X_train, y_train)
loss = result
accuracy = None

print("Loss:", loss)

print("Accuracy:", accuracy)

#Script para mantener Colab abierto

In [ ]:
from google.colab import drive
import time
import os

# Montar Google Drive en Colab
drive.mount('/content/drive')

# Función para mantener la sesión activa en Google Colab y acceder a una carpeta específica
def keep_colab_session_alive_and_interact(folder_path, interval=600):
    while True:
        try:
            # Imprime un mensaje o realiza alguna acción para mantener la sesión activa
            print("La sesión de Google Colab sigue activa.")

            # Acceder a la carpeta especificada
            folder_contents = os.listdir(folder_path)
            print("Contenido de la carpeta:", folder_contents)

        except Exception as e:
            print("Error al acceder a la carpeta:", str(e))

        time.sleep(interval)

# Ruta de la carpeta a la que deseas acceder en Google Drive
folder_path = '/content/drive/MyDrive/Colab Notebooks/Entrenamiento IA'

# Establece el intervalo de tiempo en segundos para mantener la sesión activa (por defecto, 600 segundos - 10 minutos)
keep_colab_session_alive_and_interact(folder_path, interval=600)